project 'Zhsyd_Swift.xcodeproj'
platform :ios, '9.0'
use_frameworks!

target 'Zhsyd_Swift' do

    pod 'Alamofire'
    pod 'SVProgressHUD'
    pod 'SwiftyJSON'
    pod 'TYAlertController'
    pod 'SDCycleScrollView'
    pod 'MJRefresh'

end
